
GET  http://localhost:5020/
###
POST http://localhost:5020/login
Content-Type: application/json

{
      "email":"uma@gmail.com",
      "password":"Umadevi@12"
}
###
POST http://localhost:5020/admin
Content-Type: application/json

{
         "sno":"3",
         "name":"Naresh it",
         "email": "naresh@gmail.com",
         "head":"naresh",
         "secondaryemail":"naresh@gmail.com",
         "userscount":"500",
         "primarycontact":"974323897",
         "secondarycontact":"7643756897",
         "address":"Guntur",
         "city":"hyderabad",
         "password":"uma@12",
          "InstitutionType":"collage",
          "Accessplan":"LMS",
          "selectbatchyear":"1997",
          "selectbatch":"java",
          "status":"Training",
          "expirydate":"2025",
         "code":"4042"
}
###
POST http://localhost:5020/change-password
Content-Type: application/json

{
         
         "email": "naresh@gmail.com",
         "password":"uma@126"
          
}


###
GET  http://localhost:5020/alladmin
###
GET  http://localhost:5020/alladmin/satya12@gmail.com
###
GET  http://localhost:5020/alladmin/653b825ddcfa33a32cc46e50
###
DELETE  http://localhost:5020/deleteInstitute/652fa57f443b3ee90c553f39
###
PUT  http://localhost:5020/update-data/satya12@gmail.com
Content-Type: application/json

{
        "sno":"1",
         "name":"uma",
         "email": "siva@gmail.com",
         "head":"satya",
         "secondaryemail":"satya@gmail.com",
         "userscount":"700",
         "primarycontact":"964323897",
         "secondarycontact":"76437545897",
         "address":"Guntur",
         "city":"hyderabad",
         "password":"uma@12",
          "InstitutionType":"collage",
          "Accessplan":"LMS",
         "code":"4042"
}
###
POST http://localhost:5020/assessment
Content-Type: application/json

{

     "sno":"99999",
      "examid":"2457",
      "category":"10",
      "assessmentname":"java",
      "nooftimes":"2",
      "assessmentpassword":"jsw",
      "exametype":"test",
      "cutofftype":"ss",
      "questionselection":"option",
      "assessmentreport":"good",
      "assessmentflow":"ok",
      "assessmentadaptiveness":"hh"
}
###
GET http://localhost:5020/allassessment
###
POST http://localhost:5020/courses
Content-Type: application/json

{
       "sno":"1",
      "author":"uma",
      "topic":"java",
      "lastupdate":"20",
      "aboutlearning":"ksks",
      "subscription":"ddd",
      "learn":"dd",
      "requirement":"dd",
      "difficulty":"dd",
      "coverletter":"dd"
}
###
GET http://localhost:5020/allcourses